### ISSUE TITLE
403

### ISSUE THREAD

**Issue by nahuedev** [damiansire/PedidosYa-Get-Data#1]
Me parece que bloquearon la api .... 

![image](https://user-images.githubusercontent.com/44045782/128595667-9494000c-4e4a-44b8-8629-28cd6b180477.png)

**Comment by nahuedev** [comment]
deje un bsoquejop de servicio que arme reimplementando ela funcionalidad.

https://github.com/nahuedev/service-get-data-pya.git

**Comment by damiansire** [comment]
Fijate aca, los datos que estan mandando en el headers
https://github.com/nahuedev/service-get-data-pya/blob/master/config/config.js#L25
Los cookies expiran, asi que probablemente ya hayan expirado
Tenes que entrar de nuevo al navegador y sacarlos de ahi
Probablemente haya que usar un navegador interno para que los genere en cada peticion
